Update query for delib export
3liz/lizmap-adresse-module pull request #24
Opened 2020-09-14 13:57 UTC by drillinP

PR pour répondre à la demande suivante: 
* Pour la génération du document, nous souhaiterions que soit listé toutes les voies pour lesquelles au moins un point adresse est situé sur la commune. Indépendamment donc du champ booléen deliberation qui a une autre utilité pour nous.

2020-09-21 12:23 UTC, rldhont requested changes

2020-09-21 12:23 UTC, rldhont commented on adresse/classes/search.class.php
> +    'voie_delib'=>'SELECT distinct v.nom_complet FROM adresse.voie v WHERE v.id_voie IN (select id_voie from adresse.point_adresse, adresse.commune where id_commune = id_com and insee_code = $1::text
Une requête de ce type serait plus aproprié 
```
SELECT DISTINCT v.nom_complet 
   FROM adresse.voie v 
     JOIN adresse.point_adresse p ON v.id_voie = p.id_voie
     JOIN adresse.commune c ON p.id_com = c.id_commune
WHERE c.insee_code = $1::text
```

2020-09-21 13:06 UTC, drillinP commented on adresse/classes/search.class.php
> +    'voie_delib'=>'SELECT distinct v.nom_complet FROM adresse.voie v WHERE v.id_voie IN (select id_voie from adresse.point_adresse, adresse.commune where id_commune = id_com and insee_code = $1::text
Testé en local ça marche aussi donc je l'ai appliqué

2020-09-21 14:44 UTC, rldhont approved these changes

2020-09-21 15:16 UTC, merged

2020-09-30 08:36 UTC, cbelletre commented
Serait-il possible d'ajouter également au correctif la demande suivante :
- ajouter les voies situées sur le territoire de la commune, même si elles n'ont pas de point adresse fille.
En effet, nous avons le cas de voies qui n'ont pas de points adresse (giratoire ou place par exemple) et qui doivent aussi être intégrer dans la délibération.

Merci par avance, et désolé de la demande tardive.
Clément

2020-09-30 08:53 UTC, drillinP commented
Ce correctif est déjà présent dans la dernière version du module. Il faudra donc faire un nouveau correctif pour cette demande.

Pierre