Adding module documentation
3liz/lizmap-adresse-module pull request #25
Opened 2020-09-15 15:08 UTC by drillinP

Ajout de la documentation du module.

2020-09-21 10:46 UTC, Gustry commented on docs/README.md
> +[TOC]
* Ajouter les métadonnées pour la publication sur GitHub pages
* Ajouter la commande makefile pour transformer le fichier

2020-09-21 10:46 UTC, Gustry commented on docs/README.md
> +Si vous n'avez pas encore de Projet QGIS pour le module adresse, je vous conseille de vous rendre sur [la documentation du Plugin Adresse](https://github.com/3liz/qgis-gestion_base_adresse-plugin) en
Utiliser la doc HTML, non?

2020-09-21 10:46 UTC, Gustry commented on docs/README.md
> +Maintenant que la voie sur laquelle je compte ajouter travailler est déverrouillée je peux ajouter l'adresse. Il suffit d'entrer en edition avec la couche `point_adresse` puis de placer le point la o
Tu peux paramètrer ton éditeur avec 110 caractères et faire un saut à la ligne. Cette ligne (et les autres) sont longues.

2020-09-21 10:46 UTC, Gustry commented on docs/README.md
> +Exemple: sur l'image ci-dessous, la voie à laquelle j'ajoute une adresse, son sens va de haut en bas. Sa numérotation est classique et je me situe donc à droite. Son sens de numérotation n'est pas in
```suggestion
Exemple: sur l'image ci-dessous, la voie à laquelle j'ajoute une adresse, son sens va de haut en bas. Sa numérotation est classique et je me situe donc à droite. Son sens de numérotation n'est pas inversé donc il est censé générer un numéro pair. Il n'y a pas d'adresse présente à droite donc il me donne le numéro 2 (premier nombre pair). Bien sûr vous pouvez modifier le numéro si vous en avez besoin.
```

2020-09-21 12:24 UTC, rldhont requested changes
Peux-tu faire des lignes plus courtes ? cela ne change rien à la construction des paragraphes.

2020-09-21 14:41 UTC, Gustry commented on .vscode/settings.json
> +{
Il faut ajouter `.vscode/` dans le gitignore et ne pas commiter ces fichiers

2020-09-21 14:41 UTC, Gustry commented on Makefile
> +	@docker run --rm -w /plugin -v $(shell pwd):/plugin 3liz/pymarkdown:latest docs/README.md docs/index.html
On souhaite avoir une ligne vide en fin de fichier pour éviter le symbole rouge ici

2020-09-21 14:41 UTC, Gustry commented on README.md
> +* Récupérer le dossier adresse dans https://github.com/3liz/lizmap-adresse-module
```suggestion
* Récupérer le dossier `adresse` dans https://github.com/3liz/lizmap-adresse-module
```

2020-09-21 14:41 UTC, Gustry commented on README.md
> +* Dans le répertoire où est installé lizmap, le mettre dans le dossier lizmap/lizmap-module/
```suggestion
* Dans le répertoire où est installé lizmap, le mettre dans le dossier `lizmap/lizmap-module/`
```

2020-09-21 14:41 UTC, Gustry commented on README.md
> +* Dans le fichier localconfig.ini.php qui ce situe dans lizmap/var/config il y a la partie [modules] où il faut y rajouter le niveau d’accès du module:
```suggestion
* Dans le fichier `localconfig.ini.php` qui ce situe dans `lizmap/var/config` il y a la partie `[modules]` où il faut y rajouter le niveau d’accès du module: 
```

2020-09-21 14:41 UTC, Gustry commented on README.md
> +* lancer la commande: php install/installer.php
```suggestion
* lancer la commande: `php install/installer.php`
```

2020-09-21 14:41 UTC, Gustry commented on README.md
> +  * adresse.access = 2
```suggestion
  * `adresse.access = 2`
```

2020-09-21 14:41 UTC, Gustry commented on docs/README.md
> +Pour pouvoir éditer une adresse il y a plusieurs choses à prendre en compte. Tout Commence avec la couche `voie` ou comme le montre l'image ci-dessous il y a deux styles différents. **Bleu** pour une
```suggestion
Pour pouvoir éditer une adresse il y a plusieurs choses à prendre en compte. Tout commence avec la couche `voie` ou comme le montre l'image ci-dessous il y a deux styles différents. **Bleu** pour une voie **vérouillée** et **Rouge** pour une voie **déverrouillée**.
```

2020-09-21 14:41 UTC, Gustry commented on docs/README.md
> +Maintenant que la voie sur laquelle je compte ajouter travailler est déverrouillée je peux ajouter l'adresse. Il suffit d'entrer en edition avec la couche `point_adresse` puis de placer le point la o
`je compte ajouter travailler` ?

2020-09-21 14:41 UTC, Gustry commented on docs/README.md
> +Comme on le voie ci-dessous le module ajoute un mini-dock, il est représenté dans le menu par une icône de route (dernier élément du menu). Sur ce dock on y trouve un menu de téléchargement des docum
```suggestion
Comme on le voit ci-dessous le module ajoute un mini-dock, il est représenté dans le menu par une icône de route (dernier élément du menu). Sur ce dock on y trouve un menu de téléchargement des documents pour la gestion des voie et adresse. Il y a:
```

Tu fais trop de base adresse ;-)

2020-09-21 15:27 UTC, Gustry commented on Makefile
> +
Il faut que la ligne soit vide
```suggestion

```

2020-09-21 16:00 UTC, rldhont commented on Makefile
> +
@drillinP il faut peut-être configurer ton éditeur pour supprimer les espaces inutiles en fin de ligne.

2020-09-22 08:04 UTC, Gustry approved these changes
Je mets GitHub pages dès que c'est dans master

2020-09-22 08:16 UTC, rldhont approved these changes

2020-09-22 08:17 UTC, merged