Change icon for export file
3liz/lizmap-adresse-module pull request #50
Opened 2021-11-04 14:12 UTC by drillinP

* Ticket : #49 
* Icone de type fichier pour la gestion des documents ?
![icon-file](https://user-images.githubusercontent.com/16720972/140329182-17979dc4-e842-4083-a200-e35265a0230f.jpg)

2021-11-12 10:35 UTC, rldhont commented
Pourquoi ne pas reprendre le logo du plugin ? https://github.com/3liz/qgis-gestion_base_adresse-plugin/blob/master/docs/media/icon.png

2021-11-16 08:39 UTC, rldhont requested changes

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresse.listener.php
> +        \jLog::log(gettype($lizmap_project), 'error');
log pour le développement ?

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresse.listener.php
> +                'profile not found for this project.',
message inadapté

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresse.listener.php
>              return;
renvois un tableau avec un message à la palce du log ?

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresseCheck.class.php
> +                'Adresse module error: Extension postgis missing in database',
mauvais message

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresseDockable.listener.php
> +        \jLog::log(gettype($lizmap_project), 'error');
pour le dev ?

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresseDockable.listener.php
> +            );
pas de retour de ce type dans cette méthode.

2021-11-16 08:39 UTC, rldhont commented on adresse/classes/adresseDockable.listener.php
> +            );
pas de retour de ce type dans cette méthode.

2021-11-16 09:00 UTC, drillinP commented on adresse/classes/adresse.listener.php
>              return;
il s'agit d'un listener, il faut un juste un `return;` ici ?

2021-11-16 09:05 UTC, rldhont commented on adresse/classes/adresse.listener.php
>              return;
oui, il faut tout de même décidé de ce que l'on fait des messages d'erreurs. Sachant que certains ne sont pas grave, comme le fait que le projet Lizmap ne contienne pas les couches adresse.

2021-11-16 09:17 UTC, drillinP commented on adresse/classes/adresse.listener.php
>              return;
On peut soit ne pas retourner de log soit mettre un un élément de plus dans le tableau de retour pour filtrer les éléments a retourner dans le log ?

2021-11-16 09:23 UTC, rldhont commented on adresse/classes/adresse.listener.php
>              return;
Je pense qu'il faudrait un log mais pas un error, plutot un warning ou un debug https://docs.jelix.org/en/manual-1.6/debugging

2021-11-16 09:26 UTC, drillinP commented on adresse/classes/adresse.listener.php
>              return;
A l'heure actuelle j'ai mis en warning

2021-11-16 11:08 UTC, rldhont approved these changes

2021-11-16 11:47 UTC, merged